# Generated by Django 4.2.30 on 2026-04-11 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=120)),
                ("location_governorate", models.CharField(blank=True, max_length=120)),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "funded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "minimum_investment",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "expected_roi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("funding_period_days", models.PositiveIntegerField(default=30)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("paused", "Paused"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "business_plan",
                    models.FileField(
                        blank=True, null=True, upload_to="project-documents/"
                    ),
                ),
                (
                    "financial_projections",
                    models.FileField(
                        blank=True, null=True, upload_to="project-documents/"
                    ),
                ),
                (
                    "ownership_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="project-documents/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="project-images/"
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                (
                    "ai_classified_category",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("ai_classification_at", models.DateTimeField(blank=True, null=True)),
                ("ai_generated_summary", models.TextField(blank=True)),
                ("milestone_count", models.PositiveIntegerField(default=0)),
                (
                    "repayment_status",
                    models.CharField(
                        choices=[
                            ("on_track", "On track"),
                            ("delayed", "Delayed"),
                            ("completed", "Completed"),
                        ],
                        default="on_track",
                        max_length=20,
                    ),
                ),
                (
                    "total_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("next_repayment_date", models.DateField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("investor_count", models.PositiveIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="project-images/")),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="project-documents/")),
                ("title", models.CharField(max_length=120)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.projectcategory",
            ),
        ),
    ]
