# Generated by Django 5.2 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cost_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
