# Generated by Django 5.2.16 on 2026-08-12 09:29

import apps.projects.models
import apps.projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_cost_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_plan',
            field=models.FileField(blank=True, null=True, upload_to=apps.projects.models.project_document_upload_path, validators=[apps.projects.validators.validate_project_pdf]),
        ),
        migrations.AlterField(
            model_name='project',
            name='financial_projections',
            field=models.FileField(blank=True, null=True, upload_to=apps.projects.models.project_document_upload_path, validators=[apps.projects.validators.validate_project_pdf]),
        ),
        migrations.AlterField(
            model_name='project',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to=apps.projects.models.project_document_upload_path, validators=[apps.projects.validators.validate_project_pdf]),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to=apps.projects.models.project_document_upload_path, validators=[apps.projects.validators.validate_project_pdf]),
        ),
    ]
