# Generated by Django 5.2.16 on 2026-08-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projecteditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecteditrequest',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
