# Generated by Django 5.2.13 on 2026-08-14 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_project_statuses(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for old, new in {"active": "fundraising", "successful": "fully_funded", "closed": "completed"}.items():
        Project.objects.filter(status=old).update(status=new)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_faqs_projecteditrequest_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_project_funding', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='released_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='secured_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('fundraising', 'Fundraising'), ('fully_funded', 'Fully Funded'), ('implementation', 'Implementation'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.RunPython(migrate_project_statuses, migrations.RunPython.noop),
    ]
