# Generated by Django 5.2.13 on 2026-08-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_funding_finalized_at_and_more'),
        ('investments', '0005_remove_investment_released_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='released_balance',
        ),
        migrations.RemoveField(
            model_name='project',
            name='secured_balance',
        ),
    ]
