# Generated by Django 5.2.13 on 2026-08-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_released_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecteditrequest',
            name='image_reviews',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
