# Generated by Django 5.2.16 on 2026-07-23 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('message_notifications', models.BooleanField(default=True)),
                ('project_notifications', models.BooleanField(default=True)),
                ('investment_notifications', models.BooleanField(default=True)),
                ('milestone_notifications', models.BooleanField(default=True)),
                ('repayment_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered_in_app', 'Delivered in app'), ('email_sent', 'Email sent'), ('email_failed', 'Email failed'), ('skipped', 'Skipped (preference)')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message_received', 'Message received'), ('project_submitted', 'Project submitted'), ('project_verified', 'Project verified'), ('project_rejected', 'Project rejected'), ('investment_created', 'Investment created'), ('investment_status_changed', 'Investment status changed'), ('milestone_updated', 'Milestone updated'), ('repayment_updated', 'Repayment updated'), ('system', 'System')], default='system', max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type', 'created_at'], name='notificatio_recipie_e8b7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'delivery_status', 'created_at'], name='notificatio_recipie_931db5_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user'], name='notificatio_user_id_0299fd_idx'),
        ),
    ]
