# Generated by Django 5.2.16 on 2026-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_messaging_notifications_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='in_app_visible',
            field=models.BooleanField(default=True),
        ),
    ]
