# Generated by Django 5.2.13 on 2026-08-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_email_error_notification_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message_received', 'Message received'), ('project_submitted', 'Project submitted'), ('project_verified', 'Project verified'), ('project_rejected', 'Project rejected'), ('investment_created', 'Investment created'), ('investment_status_changed', 'Investment status changed'), ('milestone_updated', 'Milestone updated'), ('repayment_updated', 'Repayment updated'), ('funding_goal_reached', 'Funding goal reached'), ('withdrawal_updated', 'Withdrawal updated'), ('funds_released', 'Funds released'), ('system', 'System')], default='system', max_length=40),
        ),
    ]
