# Generated by Django 4.2.30 on 2026-04-11 10:53

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("investor", "Investor"),
                            ("entrepreneur", "Entrepreneur"),
                            ("admin", "Admin"),
                        ],
                        default="investor",
                        max_length=20,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_kyc_verified", models.BooleanField(default=False)),
                (
                    "kyc_document",
                    models.FileField(blank=True, null=True, upload_to="kyc/"),
                ),
                ("kyc_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "investor_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                (
                    "total_invested",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_returned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_roi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "risk_preference",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("business_name", models.CharField(blank=True, max_length=150)),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("business_established_date", models.DateField(blank=True, null=True)),
                ("business_address", models.TextField(blank=True)),
                (
                    "total_funded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_repaid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reputation_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
