# Generated by Django 4.2.30 on 2026-04-11 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("investment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=120)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("paypal", "PayPal"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "expected_return",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "actual_return",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("return_received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-investment_date"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("target_date", models.DateField()),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("delayed", "Delayed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("deliverables", models.TextField(blank=True)),
                (
                    "percentage_of_project",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "funding_released",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["project", "order"],
            },
        ),
        migrations.CreateModel(
            name="Repayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("scheduled_date", models.DateField()),
                ("actual_payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("bank_transfer", "Bank transfer"),
                            ("paypal", "PayPal"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "investment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="investments.investment",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
    ]
