# Generated by Django 4.2.30 on 2026-04-11 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("investments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="investment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="repayment",
            index=models.Index(
                fields=["investment", "scheduled_date", "status"],
                name="investments_investm_713c3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["project", "status"], name="investments_project_5decb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["investor", "status", "investment_date"],
                name="investments_investo_3373cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="investment",
            index=models.Index(
                fields=["project", "status"], name="investments_project_858291_idx"
            ),
        ),
    ]
