# Generated by Django 5.2.13 on 2026-08-14 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_investment_statuses(apps, schema_editor):
    Investment = apps.get_model("investments", "Investment")
    Investment.objects.filter(status="canceled").update(status="cancelled")
    Investment.objects.filter(status="completed").update(status="released")
    Investment.objects.filter(status="pending", pending_expires_at__isnull=True).update(
        pending_expires_at=timezone.now() + timezone.timedelta(hours=24)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_initial'),
        ('projects', '0007_project_funding_finalized_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='pending_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='secured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('secured', 'Secured'), ('released', 'Released'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_investment_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evidence_description', models.TextField()),
                ('planned_expenses', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='withdrawal-evidence/%Y/%m/')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('released', 'Released'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required')], default='requested', max_length=24)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('simulated_transaction_id', models.CharField(blank=True, max_length=120)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='investments.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='projects.project')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status', 'created_at'], name='investments_project_d40195_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'under_review', 'approved'])), fields=('milestone',), name='one_open_withdrawal_per_milestone'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive')],
            },
        ),
    ]
