# Generated by Django 5.2.13 on 2026-08-14 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


def move_balances_and_normalize_investments(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Investment = apps.get_model('investments', 'Investment')
    ProjectFundingAccount = apps.get_model('investments', 'ProjectFundingAccount')

    for project in Project.objects.exclude(secured_balance=0, released_balance=0).iterator():
        ProjectFundingAccount.objects.update_or_create(
            project_id=project.pk,
            defaults={
                'secured': project.secured_balance,
                'released': project.released_balance,
                'refunded': 0,
            },
        )
    Investment.objects.filter(status__in=['secured', 'released']).update(status='confirmed')


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investment_pending_expires_at_investment_released_at_and_more'),
        ('projects', '0007_project_funding_finalized_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='secured_at',
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('released', 'Released'), ('rejected', 'Rejected'), ('revision_required', 'Revision Required'), ('cancelled', 'Cancelled')], default='requested', max_length=24),
        ),
        migrations.CreateModel(
            name='ProjectFundingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secured', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('released', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_account', to='projects.project')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('secured__gte', 0)), name='funding_account_secured_nonnegative'), models.CheckConstraint(condition=models.Q(('released__gte', 0)), name='funding_account_released_nonnegative'), models.CheckConstraint(condition=models.Q(('refunded__gte', 0)), name='funding_account_refunded_nonnegative')],
            },
        ),
        migrations.RunPython(move_balances_and_normalize_investments, migrations.RunPython.noop),
    ]
