# Generated by Django 5.2.16 on 2026-08-14 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_completed_milestones_approved(apps, schema_editor):
    milestone = apps.get_model('investments', 'Milestone')
    milestone.objects.filter(status='completed').update(completion_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_remove_investment_released_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completion_evidence',
            field=models.FileField(blank=True, null=True, upload_to='milestone-completion-evidence/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_milestone_completions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_submitted', max_length=24),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_summary',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(mark_existing_completed_milestones_approved, migrations.RunPython.noop),
    ]
