# Generated by Django 5.2.13 on 2026-08-16 18:45

import apps.investments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investments", "0012_repayment_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepaymentTransfer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("inbound_reference", models.CharField(max_length=120, unique=True)),
                ("inbound_transfer_date", models.DateField()),
                ("receipt", models.FileField(upload_to=apps.investments.models.repayment_receipt_upload_path)),
                ("source_of_funds_declaration", models.TextField()),
                ("agreement_version", models.CharField(default="repayment-funding-v1", max_length=40)),
                ("agreement_accepted_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("submitted", "Submitted"), ("under_review", "Under review"), ("verified", "Inbound transfer verified"), ("rejected", "Rejected"), ("disbursed", "Disbursed to investor")], default="submitted", max_length=24)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("outbound_reference", models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                ("disbursed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="disbursed_repayment_transfers", to=settings.AUTH_USER_MODEL)),
                ("repayment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="funding_transfer", to="investments.repayment")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_repayment_transfers", to=settings.AUTH_USER_MODEL)),
                ("submitted_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="submitted_repayment_transfers", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="investments_status_b54809_idx"),
                    models.Index(fields=["submitted_by", "created_at"], name="investments_submitt_6612a8_idx"),
                ],
                "constraints": [models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="repayment_transfer_amount_positive")],
            },
        ),
    ]
